version: '3'
services:
  web:
    build: ./web
    container_name: app
    ports:
      - "9080:9080"
      - "9443:9443"
    depends_on:
      - db
  db:
    image: ibmoms/db2express-c:latest
    container_name: db2
    ports:
      - "50000:50000"
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=Zaq12wsx
    volumes:
      - db-data:/home
    command: db2start

volumes:
  db-data: